[build]
  publish = "."
  functions = "netlify/functions"

[dev]
  publish = "."
  functions = "netlify/functions"
  port = 8888

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
